/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Datos.Pasos;
import Datos.RegistroReceta;
import com.mysql.cj.x.protobuf.MysqlxDatatypes;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Rodrigo
 */
public class AñadirPasos extends javax.swing.JDialog {

    JTextField campo = new JTextField();
    ArrayList<String> lista = new ArrayList();
    Pasos pasos = new Pasos();
    ArrayList aux = new ArrayList();
    RegistroReceta rec = new RegistroReceta();
    ArrayList lista2 = new ArrayList();
    int posY = 0, posX = 0;
    int i = 0;

    public AñadirPasos(javax.swing.JDialog parent, boolean modal) {

        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        listaPasos.removeAllItems();
        LabelPas.setText("Paso 1");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        listaPasos = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaPaso = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LabelPas = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        paso = new javax.swing.JTextField();
        atras = new javax.swing.JButton();

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(17, 17, 17));
        jPanel3.setForeground(new java.awt.Color(17, 17, 17));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/hamburger (2)_1.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        listaPasos.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        listaPasos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        listaPasos.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        listaPasos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listaPasos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaPasosActionPerformed(evt);
            }
        });
        jPanel3.add(listaPasos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 136, 40));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Qué paso quiere modificar?");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Guardar ");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnanaranjado.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, -1, -1));

        areaPaso.setColumns(20);
        areaPaso.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        areaPaso.setRows(5);
        areaPaso.setBorder(null);
        jScrollPane2.setViewportView(areaPaso);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 250, 130));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Borrar Pasos");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 80, 20));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnanaranjadolargo.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 370, 470));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel13.setText("Añadir Paso");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tituloPas_1.png"))); // NOI18N
        jLabel1.setText("PASOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 380, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 80)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnbotoncito.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 230, 70));

        jLabel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel3MouseDragged(evt);
            }
        });
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 560, 48));

        LabelPas.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        LabelPas.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(LabelPas, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 130, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("_________________________");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 300, -1));

        paso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        paso.setForeground(new java.awt.Color(102, 102, 102));
        paso.setBorder(null);
        paso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pasoFocusGained(evt);
            }
        });
        paso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pasoMouseClicked(evt);
            }
        });
        paso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasoActionPerformed(evt);
            }
        });
        jPanel1.add(paso, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 280, 30));

        atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-back-50.png"))); // NOI18N
        atras.setContentAreaFilled(false);
        atras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        atras.setDefaultCapable(false);
        atras.setEnabled(false);
        atras.setFocusPainted(false);
        atras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atrasMouseClicked(evt);
            }
        });
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });
        jPanel1.add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 60, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked

        //[255,87,34]NARANJITA LINDO
        if (!paso.getText().equals("")) {
            lista.add(paso.getText());
            LabelPas.setText("Paso " + (i + 2));
            i++;
            listaPasos.addItem("Paso " + i);
            for (int j = 0; j < lista.size(); j++) {
                pasos.setNombre(lista);
            }

        }
        paso.setText("");

    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed

        posX = evt.getX();
        posY = evt.getY();

    }//GEN-LAST:event_jLabel3MousePressed

    private void jLabel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseDragged
        setLocation(evt.getXOnScreen() - posX, evt.getYOnScreen() - posY);
    }//GEN-LAST:event_jLabel3MouseDragged

    private void pasoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pasoMouseClicked

    }//GEN-LAST:event_pasoMouseClicked

    private void pasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pasoActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked

        int pos = jPanel3.getX();
        if (pos > 500) {
            Animacion.Animacion.mover_izquierda(640, 320, 2, 2, jPanel3);
            //Animacion.Animacion.mover_izquierda(630, 310, 2, 2, jPanel3);

        } else {
            Animacion.Animacion.mover_derecha(320, 640, 2, 2, jPanel3);
            //Animacion.Animacion.mover_derecha(310, 630, 2, 2, jPanel3);

        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void listaPasosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaPasosActionPerformed

        int io = 0;
        for (int j = 0; j < listaPasos.getItemCount(); j++) {
            io = listaPasos.getSelectedIndex();
        }
        for (int j = 0; j < lista.size(); j++) {
            areaPaso.setText(lista.get(io));
        }

    }//GEN-LAST:event_listaPasosActionPerformed

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed


    }//GEN-LAST:event_atrasActionPerformed

    private void atrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasMouseClicked

        AñadirReceta añ = new AñadirReceta();
        añ.requestFocus();
        this.dispose();
        
    }//GEN-LAST:event_atrasMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        int io = listaPasos.getSelectedIndex();
        if (areaPaso.getText().equals("")) {
            int count = listaPasos.getItemCount();
            if (count == io + 1) {
                lista.remove(io);
                listaPasos.removeItemAt(io);
                i = i - 1;
                LabelPas.setText("Paso " + (i + 1));
            } else {
                JOptionPane.showMessageDialog(null, "Sólo se puede borrar el último paso");
            }
        } else {
            lista.set(io, areaPaso.getText());
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked

        int confirmar = JOptionPane.showConfirmDialog(null, "¿Desea eliminar todos los pasos?", "", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (confirmar == 0) {
            int io = listaPasos.getItemCount();
            lista.clear();
            listaPasos.removeAllItems();
            i = 0;
            LabelPas.setText("Paso " + (i + 1));
            areaPaso.setText("");
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void pasoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pasoFocusGained

        int pos = jPanel3.getX();
        if (pos < 500) {

           Animacion.Animacion.mover_derecha(320, 640, 2, 2, jPanel3);
        }


    }//GEN-LAST:event_pasoFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelPas;
    private javax.swing.JTextArea areaPaso;
    private javax.swing.JButton atras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> listaPasos;
    private javax.swing.JTextField paso;
    // End of variables declaration//GEN-END:variables
}
