/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Datos.Buscar;
import Datos.ModificarRec;
import Conexion.SQL;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Mati
 */
public class BotonModificar extends javax.swing.JFrame {

    ArrayList aliNom = new ArrayList();
    ArrayList aliIng = new ArrayList();
    ArrayList aliCant = new ArrayList();
    ArrayList aliUni = new ArrayList();
    SQL sql = new SQL();

    public BotonModificar() {
        initComponents();

        this.setLocationRelativeTo(null);
        try {
            setIconImage(new ImageIcon(getClass().getResource("../Imagenes/icono.png")).getImage());
        } catch (Exception e) {

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBusqueda = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        LabelCalorias1 = new javax.swing.JLabel();
        LabelCalorias2 = new javax.swing.JLabel();
        LabelDuracion = new javax.swing.JLabel();
        LabelNombre = new javax.swing.JLabel();
        labelPaso = new javax.swing.JLabel();
        LabelIngrediente = new javax.swing.JLabel();
        LabelDificultad = new javax.swing.JLabel();
        LabelTipo = new javax.swing.JLabel();
        PanelTitulo = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        PanelNombre = new javax.swing.JPanel();
        nuevo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BuscarNombre = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        actual = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        PanelDificultad = new javax.swing.JPanel();
        ComboDificultad = new javax.swing.JComboBox<>();
        BuscarDificultad = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        difActual = new javax.swing.JLabel();
        PanelTipo = new javax.swing.JPanel();
        ComboTipo = new javax.swing.JComboBox<>();
        buscarTipo = new javax.swing.JLabel();
        jlabel = new javax.swing.JLabel();
        jlabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tipoActual = new javax.swing.JLabel();
        PanelIngrediente = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        modIng = new javax.swing.JLabel();
        comboIngNuevo = new javax.swing.JComboBox<>();
        jLabel33 = new javax.swing.JLabel();
        campoCant = new javax.swing.JTextField();
        comboIng = new javax.swing.JComboBox<>();
        labelCant = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        comboUni = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        labelUni = new javax.swing.JLabel();
        PanelDesc = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        modDesc = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descNueva = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        descActual = new javax.swing.JTextArea();
        PanelCom = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        modCom = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        comNuevo = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        comActual = new javax.swing.JTextArea();
        PanelDur = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        durActual = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        durBuscar = new javax.swing.JLabel();
        durNueva = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelBusqueda.setBackground(new java.awt.Color(255, 204, 204));
        PanelBusqueda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-back-50.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        PanelBusqueda.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        LabelCalorias1.setFont(new java.awt.Font("Segoe UI Black", 1, 32)); // NOI18N
        LabelCalorias1.setForeground(new java.awt.Color(51, 51, 51));
        LabelCalorias1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelCalorias1.setText(" Comentarios");
        LabelCalorias1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LabelCalorias1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelCalorias1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LabelCalorias1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LabelCalorias1MouseExited(evt);
            }
        });
        PanelBusqueda.add(LabelCalorias1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, 240, 50));

        LabelCalorias2.setFont(new java.awt.Font("Segoe UI Black", 1, 32)); // NOI18N
        LabelCalorias2.setForeground(new java.awt.Color(51, 51, 51));
        LabelCalorias2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelCalorias2.setText(" Descripción");
        LabelCalorias2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LabelCalorias2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelCalorias2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LabelCalorias2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LabelCalorias2MouseExited(evt);
            }
        });
        PanelBusqueda.add(LabelCalorias2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, 230, 50));

        LabelDuracion.setFont(new java.awt.Font("Segoe UI Black", 1, 32)); // NOI18N
        LabelDuracion.setForeground(new java.awt.Color(51, 51, 51));
        LabelDuracion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelDuracion.setText("Duración");
        LabelDuracion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LabelDuracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelDuracionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LabelDuracionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LabelDuracionMouseExited(evt);
            }
        });
        PanelBusqueda.add(LabelDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 170, 50));

        LabelNombre.setBackground(new java.awt.Color(102, 102, 102));
        LabelNombre.setFont(new java.awt.Font("Segoe UI Black", 1, 32)); // NOI18N
        LabelNombre.setForeground(new java.awt.Color(51, 51, 51));
        LabelNombre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelNombre.setText("Nombre");
        LabelNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LabelNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelNombreMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LabelNombreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LabelNombreMouseExited(evt);
            }
        });
        PanelBusqueda.add(LabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 150, 50));

        labelPaso.setBackground(new java.awt.Color(255, 255, 255));
        labelPaso.setFont(new java.awt.Font("Segoe UI Black", 1, 32)); // NOI18N
        labelPaso.setForeground(new java.awt.Color(51, 51, 51));
        labelPaso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPaso.setText(" Paso");
        labelPaso.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        labelPaso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelPasoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelPasoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelPasoMouseExited(evt);
            }
        });
        PanelBusqueda.add(labelPaso, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 100, 50));

        LabelIngrediente.setFont(new java.awt.Font("Segoe UI Black", 1, 32)); // NOI18N
        LabelIngrediente.setForeground(new java.awt.Color(51, 51, 51));
        LabelIngrediente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelIngrediente.setText(" Ingrediente");
        LabelIngrediente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LabelIngrediente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelIngredienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LabelIngredienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LabelIngredienteMouseExited(evt);
            }
        });
        PanelBusqueda.add(LabelIngrediente, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, -1, 40));

        LabelDificultad.setFont(new java.awt.Font("Segoe UI Black", 1, 32)); // NOI18N
        LabelDificultad.setForeground(new java.awt.Color(51, 51, 51));
        LabelDificultad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelDificultad.setText(" Dificultad");
        LabelDificultad.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LabelDificultad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelDificultadMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LabelDificultadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LabelDificultadMouseExited(evt);
            }
        });
        PanelBusqueda.add(LabelDificultad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 190, 50));

        LabelTipo.setFont(new java.awt.Font("Segoe UI Black", 1, 32)); // NOI18N
        LabelTipo.setForeground(new java.awt.Color(51, 51, 51));
        LabelTipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTipo.setText(" Tipo");
        LabelTipo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LabelTipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelTipoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LabelTipoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LabelTipoMouseExited(evt);
            }
        });
        PanelBusqueda.add(LabelTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 130, 40));

        PanelTitulo.setBackground(new java.awt.Color(255, 204, 204));

        jLabel6.setBackground(new java.awt.Color(51, 51, 51));
        jLabel6.setFont(new java.awt.Font("Montserrat", 1, 65)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Modificar");

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("¿Qué quiere modificar?");

        javax.swing.GroupLayout PanelTituloLayout = new javax.swing.GroupLayout(PanelTitulo);
        PanelTitulo.setLayout(PanelTituloLayout);
        PanelTituloLayout.setHorizontalGroup(
            PanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTituloLayout.createSequentialGroup()
                .addContainerGap(182, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(200, 200, 200))
            .addGroup(PanelTituloLayout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelTituloLayout.setVerticalGroup(
            PanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTituloLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        PanelBusqueda.add(PanelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, -190, 730, 190));

        PanelNombre.setBackground(new java.awt.Color(255, 204, 204));
        PanelNombre.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nuevo.setBackground(new java.awt.Color(255, 204, 204));
        nuevo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        nuevo.setForeground(new java.awt.Color(255, 255, 255));
        nuevo.setBorder(null);
        PanelNombre.add(nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 280, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Nuevo");
        PanelNombre.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 110, 50));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("______________________________________________________________________");
        jLabel4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel4FocusGained(evt);
            }
        });
        PanelNombre.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 290, 10));

        BuscarNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-arrow-100.png"))); // NOI18N
        BuscarNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BuscarNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscarNombreMouseClicked(evt);
            }
        });
        PanelNombre.add(BuscarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Actual");
        PanelNombre.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 100, 50));

        actual.setBackground(new java.awt.Color(255, 204, 204));
        actual.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        actual.setForeground(new java.awt.Color(255, 255, 255));
        actual.setBorder(null);
        actual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualActionPerformed(evt);
            }
        });
        PanelNombre.add(actual, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 280, 40));

        jLabel19.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("______________________________________________________________________");
        jLabel19.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel19FocusGained(evt);
            }
        });
        PanelNombre.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 290, 10));

        PanelBusqueda.add(PanelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, -175, 640, 170));

        PanelDificultad.setBackground(new java.awt.Color(51, 51, 51));
        PanelDificultad.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ComboDificultad.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        ComboDificultad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fácil", "Media", "Difícil" }));
        PanelDificultad.add(ComboDificultad, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 190, 63));

        BuscarDificultad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-search-64 (2).png"))); // NOI18N
        BuscarDificultad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscarDificultadMouseClicked(evt);
            }
        });
        PanelDificultad.add(BuscarDificultad, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Nuevo");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        PanelDificultad.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Actual");
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        PanelDificultad.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        difActual.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(difActual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(difActual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        PanelDificultad.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 180, 60));

        PanelBusqueda.add(PanelDificultad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, -195, 700, 190));

        PanelTipo.setBackground(new java.awt.Color(51, 51, 51));
        PanelTipo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ComboTipo.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        ComboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Postres", "Carnes", "Pastas", "Ensalada", "Plato Principal", " " }));
        PanelTipo.add(ComboTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 250, 63));

        buscarTipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-search-64 (2).png"))); // NOI18N
        buscarTipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarTipoMouseClicked(evt);
            }
        });
        PanelTipo.add(buscarTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        jlabel.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jlabel.setForeground(new java.awt.Color(255, 255, 255));
        jlabel.setText("Actual");
        jlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabelMouseClicked(evt);
            }
        });
        PanelTipo.add(jlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, 64));

        jlabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jlabel1.setForeground(new java.awt.Color(255, 255, 255));
        jlabel1.setText("Nuevo");
        jlabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel1MouseClicked(evt);
            }
        });
        PanelTipo.add(jlabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, -1, 64));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tipoActual.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jPanel1.add(tipoActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 60));

        PanelTipo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 230, 60));

        PanelBusqueda.add(PanelTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, -195, 720, 190));

        PanelIngrediente.setBackground(new java.awt.Color(51, 51, 51));
        PanelIngrediente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Búsqueda");
        PanelIngrediente.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 150, 50));

        modIng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-search-50 (1).png"))); // NOI18N
        modIng.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        modIng.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modIngMouseClicked(evt);
            }
        });
        PanelIngrediente.add(modIng, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 50, -1));

        comboIngNuevo.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        comboIngNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboIngNuevoActionPerformed(evt);
            }
        });
        PanelIngrediente.add(comboIngNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 260, 70));

        jLabel33.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("_______________");
        jLabel33.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel33FocusGained(evt);
            }
        });
        PanelIngrediente.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 60, 10));

        campoCant.setBackground(new java.awt.Color(51, 51, 51));
        campoCant.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        campoCant.setForeground(new java.awt.Color(255, 255, 255));
        campoCant.setBorder(null);
        campoCant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCantActionPerformed(evt);
            }
        });
        PanelIngrediente.add(campoCant, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 60, 40));

        comboIng.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        comboIng.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboIngItemStateChanged(evt);
            }
        });
        PanelIngrediente.add(comboIng, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 260, 70));

        labelCant.setBackground(new java.awt.Color(51, 51, 51));
        labelCant.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        labelCant.setForeground(new java.awt.Color(255, 255, 255));
        labelCant.setBorder(null);
        labelCant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelCantActionPerformed(evt);
            }
        });
        PanelIngrediente.add(labelCant, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 60, 40));

        jLabel34.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("_______________");
        jLabel34.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel34FocusGained(evt);
            }
        });
        PanelIngrediente.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 60, 10));

        comboUni.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        comboUni.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "gramos", "unidad", "kilos", "libras" }));
        PanelIngrediente.add(comboUni, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, 80, 50));

        labelUni.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        labelUni.setText("jLabel1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(labelUni, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(16, Short.MAX_VALUE)
                    .addComponent(labelUni)
                    .addContainerGap(15, Short.MAX_VALUE)))
        );

        PanelIngrediente.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 80, 50));

        PanelBusqueda.add(PanelIngrediente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 770, 230));

        PanelDesc.setBackground(new java.awt.Color(255, 204, 204));
        PanelDesc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23.setText("Nueva");
        PanelDesc.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 110, 50));

        jLabel24.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 51));
        jLabel24.setText("______________________________________________________________________");
        jLabel24.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel24FocusGained(evt);
            }
        });
        PanelDesc.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 290, 10));

        modDesc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-arrow-100.png"))); // NOI18N
        modDesc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        modDesc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modDescMouseClicked(evt);
            }
        });
        PanelDesc.add(modDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 51, 51));
        jLabel25.setText("Actual");
        PanelDesc.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 100, 50));

        jLabel26.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 51, 51));
        jLabel26.setText("______________________________________________________________________");
        jLabel26.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel26FocusGained(evt);
            }
        });
        PanelDesc.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 290, 40));

        descNueva.setColumns(20);
        descNueva.setRows(5);
        jScrollPane1.setViewportView(descNueva);

        PanelDesc.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 240, 100));

        descActual.setColumns(20);
        descActual.setRows(5);
        jScrollPane2.setViewportView(descActual);

        PanelDesc.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 240, 100));

        PanelBusqueda.add(PanelDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, -175, 750, 170));

        PanelCom.setBackground(new java.awt.Color(255, 204, 204));
        PanelCom.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 51, 51));
        jLabel27.setText("Nuevo");
        PanelCom.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 110, 50));

        jLabel28.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 51, 51));
        jLabel28.setText("______________________________________________________________________");
        jLabel28.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel28FocusGained(evt);
            }
        });
        PanelCom.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 290, 10));

        modCom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-arrow-100.png"))); // NOI18N
        modCom.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        modCom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modComMouseClicked(evt);
            }
        });
        PanelCom.add(modCom, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        jLabel29.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 51, 51));
        jLabel29.setText("Comentario actual");
        PanelCom.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 50));

        jLabel30.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(51, 51, 51));
        jLabel30.setText("______________________________________________________________________");
        jLabel30.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel30FocusGained(evt);
            }
        });
        PanelCom.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 290, 40));

        comNuevo.setColumns(20);
        comNuevo.setRows(5);
        jScrollPane3.setViewportView(comNuevo);

        PanelCom.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 240, 100));

        comActual.setColumns(20);
        comActual.setRows(5);
        jScrollPane4.setViewportView(comActual);

        PanelCom.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 240, 100));

        PanelBusqueda.add(PanelCom, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, -175, 750, 170));

        PanelDur.setBackground(new java.awt.Color(51, 51, 51));
        PanelDur.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel31.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Nueva ");
        PanelDur.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 110, 40));

        jLabel32.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Duracion actual");
        PanelDur.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, 32));

        durActual.setBackground(new java.awt.Color(51, 51, 51));
        durActual.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        durActual.setForeground(new java.awt.Color(204, 204, 204));
        durActual.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        durActual.setBorder(null);
        PanelDur.add(durActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 140, 39));
        PanelDur.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 140, 10));
        PanelDur.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 140, 10));

        durBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-search-50 (1).png"))); // NOI18N
        durBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                durBuscarMouseClicked(evt);
            }
        });
        PanelDur.add(durBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));

        durNueva.setBackground(new java.awt.Color(51, 51, 51));
        durNueva.setBorder(null);
        durNueva.setForeground(new java.awt.Color(204, 204, 204));
        try {
            durNueva.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        durNueva.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        durNueva.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        PanelDur.add(durNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 140, 40));

        PanelBusqueda.add(PanelDur, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, -145, 540, 140));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LabelDuracionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelDuracionMouseClicked

        durActual.setText(ModificarRec.getDuracion());

        int y = PanelTitulo.getY();
        //  int y2 = PanelCosto.getY();
        int y3 = PanelNombre.getY();

        int y5 = PanelDificultad.getY();
        int y6 = PanelTipo.getY();
        int y7 = PanelIngrediente.getY();

        if (y > -1) {
            Animacion.Animacion.subir(30, -190, 2, 3, PanelTitulo);
            Animacion.Animacion.bajar(-145, 30, 2, 3, PanelDur);

            //  } else if (y2 > 0) {
            //      Animacion.Animacion.subir(30, -145, 2, 3, PanelCosto);
            //      Animacion.Animacion.bajar(-145, 30, 2, 3, PanelDur);
        } else if (y3 > 0) {
            Animacion.Animacion.subir(30, -190, 2, 3, PanelNombre);
            Animacion.Animacion.bajar(-145, 30, 2, 3, PanelDur);
        } else if (y5 > 0) {
            Animacion.Animacion.subir(30, -195, 2, 3, PanelDificultad);
            Animacion.Animacion.bajar(-145, 30, 2, 3, PanelDur);
        } else if (y6 > 0) {
            Animacion.Animacion.subir(30, -195, 2, 3, PanelTipo);
            Animacion.Animacion.bajar(-145, 30, 2, 3, PanelDur);

        } else if (y7 > 0) {
            Animacion.Animacion.subir(30, -195, 2, 3, PanelIngrediente);
            Animacion.Animacion.bajar(-145, 30, 2, 3, PanelDur);

        }
    }//GEN-LAST:event_LabelDuracionMouseClicked

    private void LabelDuracionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelDuracionMouseEntered
        LabelDuracion.setForeground(new Color(204, 204, 204));
    }//GEN-LAST:event_LabelDuracionMouseEntered

    private void LabelDuracionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelDuracionMouseExited
        LabelDuracion.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_LabelDuracionMouseExited

    private void LabelNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelNombreMouseClicked
        SQL sql = new SQL();

        actual.setText(ModificarRec.getNombre());

        int y = PanelTitulo.getY();
        //  int y2 = PanelCosto.getY();

        int y4 = PanelDur.getY();
        int y5 = PanelDificultad.getY();
        int y6 = PanelTipo.getY();
        int y7 = PanelIngrediente.getY();

        if (y > -1) {

            Animacion.Animacion.subir(30, -190, 2, 3, PanelTitulo);
            Animacion.Animacion.bajar(-175, 30, 2, 3, PanelNombre);
            // } else if (y2 > 0) {
            //     Animacion.Animacion.subir(30, -190, 2, 3, PanelCosto);
            //     Animacion.Animacion.bajar(-175, 30, 2, 3, PanelNombre);

        } else if (y4 > 0) {
            Animacion.Animacion.subir(30, -145, 2, 3, PanelDur);
            Animacion.Animacion.bajar(-175, 30, 2, 3, PanelNombre);
        } else if (y5 > 0) {
            Animacion.Animacion.subir(30, -195, 2, 3, PanelDificultad);
            Animacion.Animacion.bajar(-175, 30, 2, 3, PanelNombre);
        } else if (y6 > 0) {
            Animacion.Animacion.subir(30, -195, 2, 3, PanelTipo);
            Animacion.Animacion.bajar(-175, 30, 2, 3, PanelNombre);

        } else if (y7 > 0) {
            Animacion.Animacion.subir(30, -195, 2, 3, PanelIngrediente);
            Animacion.Animacion.bajar(-175, 30, 2, 3, PanelNombre);

        }
    }//GEN-LAST:event_LabelNombreMouseClicked

    private void LabelNombreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelNombreMouseEntered
        LabelNombre.setForeground(new Color(204, 204, 204));
    }//GEN-LAST:event_LabelNombreMouseEntered

    private void LabelNombreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelNombreMouseExited
        LabelNombre.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_LabelNombreMouseExited

    private void labelPasoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPasoMouseClicked
        /*
        int y = PanelTitulo.getY();

        int y3 = PanelNombre.getY();
        int y4 = PanelDur.getY();
        int y5 = PanelDificultad.getY();
        int y6 = PanelTipo.getY();
        int y7 = PanelIngrediente.getY();

        if (y > -1) {
            Animacion.Animacion.subir(30, -190, 2, 3, PanelTitulo);
            Animacion.Animacion.bajar(-145, 30, 2, 3, PanelCosto);

        } else if (y3 > 0) {
            Animacion.Animacion.subir(30, -190, 2, 3, PanelNombre);
            Animacion.Animacion.bajar(-145, 30, 2, 3, PanelCosto);
        } else if (y4 > 0) {
            Animacion.Animacion.subir(30, -145, 2, 3, PanelDur);
            Animacion.Animacion.bajar(-145, 30, 2, 3, PanelCosto);
        } else if (y5 > 0) {
            Animacion.Animacion.subir(30, -195, 2, 3, PanelDificultad);
            Animacion.Animacion.bajar(-145, 30, 2, 3, PanelCosto);
        } else if (y6 > 0) {
            Animacion.Animacion.subir(30, -195, 2, 3, PanelTipo);
            Animacion.Animacion.bajar(-145, 30, 2, 3, PanelCosto);

        } else if (y7 > 0) {
            Animacion.Animacion.subir(30, -195, 2, 3, PanelIngrediente);
            Animacion.Animacion.bajar(-145, 30, 2, 3, PanelCosto);

        }*/
    }//GEN-LAST:event_labelPasoMouseClicked

    private void labelPasoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPasoMouseEntered
        labelPaso.setForeground(new Color(204, 204, 204));
    }//GEN-LAST:event_labelPasoMouseEntered

    private void labelPasoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPasoMouseExited
        labelPaso.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_labelPasoMouseExited

    private void LabelIngredienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelIngredienteMouseClicked

        aliIng = sql.traerIngrediente();

        for (int i = 0; i < aliIng.size(); i++) {
            comboIngNuevo.addItem((String) aliIng.get(i));
        }

        aliNom = sql.modificarIng("SELECT nombreingrediente FROM recetas_has_ingrediente, ingrediente WHERE id_receta = ? and ingrediente.id_ingrediente = recetas_has_ingrediente.ingrediente",
                "nombreingrediente", ModificarRec.getId());
        aliCant = sql.modificarIng("SELECT cantidad FROM recetas_has_ingrediente, ingrediente WHERE id_receta = ? and ingrediente.id_ingrediente = recetas_has_ingrediente.ingrediente",
                "cantidad", ModificarRec.getId());
        aliUni = sql.modificarIng("SELECT unidad FROM recetas_has_ingrediente, ingrediente WHERE id_receta = ? and ingrediente.id_ingrediente = recetas_has_ingrediente.ingrediente",
                "unidad", ModificarRec.getId());

        for (int i = 0; i < aliCant.size(); i++) {

            comboIng.addItem((String) aliNom.get(i));
            labelCant.setText(aliCant.get(i).toString());
            labelUni.setText((String) aliUni.get(0));

        }

        int y = PanelTitulo.getY();
        //int y2 = PanelCosto.getY();
        int y3 = PanelNombre.getY();
        int y4 = PanelDur.getY();
        int y5 = PanelDificultad.getY();
        int y6 = PanelTipo.getY();

        if (y > -1) {

            Animacion.Animacion.subir(30, -190, 2, 3, PanelTitulo);
            Animacion.Animacion.bajar(-175, 30, 2, 3, PanelIngrediente);
            // } else if (y2 > 0) {
            //     Animacion.Animacion.subir(30, -190, 2, 3, PanelCosto);
            //     Animacion.Animacion.bajar(-175, 30, 2, 3, PanelIngrediente);
        } else if (y3 > 0) {
            Animacion.Animacion.subir(30, -190, 2, 3, PanelNombre);
            Animacion.Animacion.bajar(-175, 30, 2, 3, PanelIngrediente);
        } else if (y4 > 0) {
            Animacion.Animacion.subir(30, -145, 2, 3, PanelDur);
            Animacion.Animacion.bajar(-175, 30, 2, 3, PanelIngrediente);
        } else if (y5 > 0) {
            Animacion.Animacion.subir(30, -195, 2, 3, PanelDificultad);
            Animacion.Animacion.bajar(-175, 30, 2, 3, PanelIngrediente);
        } else if (y6 > 0) {
            Animacion.Animacion.subir(30, -195, 2, 3, PanelTipo);
            Animacion.Animacion.bajar(-175, 30, 2, 3, PanelIngrediente);

        }


    }//GEN-LAST:event_LabelIngredienteMouseClicked

    private void LabelIngredienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelIngredienteMouseEntered
        LabelIngrediente.setForeground(new Color(204, 204, 204));
    }//GEN-LAST:event_LabelIngredienteMouseEntered

    private void LabelIngredienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelIngredienteMouseExited
        LabelIngrediente.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_LabelIngredienteMouseExited

    private void LabelDificultadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelDificultadMouseClicked

        difActual.setText(ModificarRec.getDificultad());

        int y = PanelTitulo.getY();
        //int y2 = PanelCosto.getY();
        int y3 = PanelNombre.getY();
        int y4 = PanelDur.getY();

        int y6 = PanelTipo.getY();
        int y7 = PanelIngrediente.getY();

        if (y > -1) {
            Animacion.Animacion.subir(30, -195, 2, 3, PanelTitulo);
            Animacion.Animacion.bajar(-195, 30, 2, 3, PanelDificultad);

            // } else if (y2 > 0) {
            //     Animacion.Animacion.subir(30, -195, 2, 3, PanelCosto);
            //     Animacion.Animacion.bajar(-195, 30, 2, 3, PanelDificultad);
        } else if (y3 > 0) {
            Animacion.Animacion.subir(30, -195, 2, 3, PanelNombre);
            Animacion.Animacion.bajar(-195, 30, 2, 3, PanelDificultad);
        } else if (y4 > 0) {
            Animacion.Animacion.subir(30, -195, 2, 3, PanelDur);
            Animacion.Animacion.bajar(-195, 30, 2, 3, PanelDificultad);
        } else if (y6 > 0) {
            Animacion.Animacion.subir(30, -195, 2, 3, PanelTipo);
            Animacion.Animacion.bajar(-195, 30, 2, 3, PanelDificultad);
        } else if (y7 > 0) {
            Animacion.Animacion.subir(30, -195, 2, 3, PanelIngrediente);
            Animacion.Animacion.bajar(-195, 30, 2, 3, PanelDificultad);

        }
    }//GEN-LAST:event_LabelDificultadMouseClicked

    private void LabelDificultadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelDificultadMouseEntered
        LabelDificultad.setForeground(new Color(204, 204, 204));
    }//GEN-LAST:event_LabelDificultadMouseEntered

    private void LabelDificultadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelDificultadMouseExited
        LabelDificultad.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_LabelDificultadMouseExited

    private void LabelTipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelTipoMouseClicked
        tipoActual.setText(ModificarRec.getTipo());
        int y = PanelTitulo.getY();
        //int y2 = PanelCosto.getY();
        int y3 = PanelNombre.getY();
        int y4 = PanelDur.getY();
        int y5 = PanelDificultad.getY();

        int y7 = PanelIngrediente.getY();
        if (y > -1) {
            Animacion.Animacion.subir(30, -190, 2, 3, PanelTitulo);
            Animacion.Animacion.bajar(-195, 30, 2, 3, PanelTipo);

            // } else if (y2 > 0) {
            //    Animacion.Animacion.subir(30, -145, 2, 3, PanelCosto);
            //     Animacion.Animacion.bajar(-195, 30, 2, 3, PanelTipo);
        } else if (y3 > 0) {
            Animacion.Animacion.subir(30, -190, 2, 3, PanelNombre);
            Animacion.Animacion.bajar(-195, 30, 2, 3, PanelTipo);
        } else if (y4 > 0) {
            Animacion.Animacion.subir(30, -145, 2, 3, PanelDur);
            Animacion.Animacion.bajar(-195, 30, 2, 3, PanelTipo);
        } else if (y5 > 0) {
            Animacion.Animacion.subir(30, -195, 2, 3, PanelDificultad);
            Animacion.Animacion.bajar(-195, 30, 2, 3, PanelTipo);
        } else if (y7 > 0) {
            Animacion.Animacion.subir(30, -195, 2, 3, PanelIngrediente);
            Animacion.Animacion.bajar(-15, 30, 2, 3, PanelTipo);

        }
    }//GEN-LAST:event_LabelTipoMouseClicked

    private void LabelTipoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelTipoMouseEntered
        LabelTipo.setForeground(new Color(204, 204, 204));
    }//GEN-LAST:event_LabelTipoMouseEntered

    private void LabelTipoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelTipoMouseExited
        LabelTipo.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_LabelTipoMouseExited

    private void jLabel4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel4FocusGained

    }//GEN-LAST:event_jLabel4FocusGained

    private void BuscarNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarNombreMouseClicked

        ModificarRec.setNuevoNombre(nuevo.getText());

        if (!nuevo.getText().equals("")) {
            if (!nuevo.getText().equals(actual.getText())) {

                if (sql.updateReceta("UPDATE recetas SET nombre = ? WHERE id_receta = ? ", ModificarRec.getNuevoNombre(), ModificarRec.getId())) {
                    System.out.println("success");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Valor ingresado igual al actual");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Debe ingresar un valor nuevo ");
        }


    }//GEN-LAST:event_BuscarNombreMouseClicked

    private void jLabel19FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel19FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel19FocusGained

    private void BuscarDificultadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarDificultadMouseClicked

        ModificarRec.setNuevaDificultad((String) ComboDificultad.getSelectedItem());

        if (!ComboDificultad.getSelectedItem().equals(difActual.getText())) {
            if (sql.updateReceta("UPDATE recetas SET dificultadreceta = ? WHERE id_receta =? ", ModificarRec.getNuevaDificultad(), ModificarRec.getId())) {
                System.out.println("success");
            } else {
                System.out.println("error");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Valor ingresado igual al actual");
        }


    }//GEN-LAST:event_BuscarDificultadMouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked

    }//GEN-LAST:event_jLabel18MouseClicked

    private void buscarTipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarTipoMouseClicked

        ModificarRec.setNuevoTipo((String) ComboTipo.getSelectedItem());

        if (!ComboTipo.getSelectedItem().equals(tipoActual.getText())) {
            if (sql.updateReceta("UPDATE recetas SET tiporeceta = ? WHERE id_receta =? ", ModificarRec.getNuevoTipo(), ModificarRec.getId())) {
                System.out.println("success");
            } else {
                System.out.println("error");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Valor ingresado igual al actual");
        }


    }//GEN-LAST:event_buscarTipoMouseClicked

    private void jlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabelMouseClicked

    }//GEN-LAST:event_jlabelMouseClicked

    private void modIngMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modIngMouseClicked

       
        
        ModificarRec.setNuevoNomIngrediente((String) comboIngNuevo.getSelectedItem());
        ModificarRec.setNuevaUnidadIngrediente((String) comboUni.getSelectedItem());
        ModificarRec.setNuevaCantIngrediente(campoCant.getText());
//||

        String nomActual = sql.modificarIng("SELECT id_ingrediente FROM ingrediente WHERE nombreingrediente = ?", ModificarRec.getNuevoNomIngrediente());
        String nomNuevo = sql.modificarIng("SELECT id_ingrediente FROM ingrediente WHERE nombreingrediente = ?", (String) comboIng.getSelectedItem());
        
        String uniActual = sql.modificarIng("SELECT ingrediente FROM recetas_has_ingrediente WHERE unidad = ?", ModificarRec.getNuevaUnidadIngrediente());
        String uniNuevo = sql.modificarIng("SELECT ingrediente FROM recetas_has_ingrediente WHERE unidad = ?", (String) comboUni.getSelectedItem());
        
        
        
        if (sql.updateIngrediente("update recetas_has_ingrediente SET ingrediente = ? where id_receta = ? and ingrediente = ?", nomActual, ModificarRec.getId(), nomNuevo)) {
            if (sql.updateIngrediente("update recetas_has_ingrediente SET ingrediente = ? where id_receta = ? and ingrediente = ?", nomActual, ModificarRec.getId(), nomNuevo)) {
            
            System.out.println("success");
            aliNom = sql.modificarIng("SELECT nombreingrediente FROM recetas_has_ingrediente, ingrediente WHERE id_receta = ? and ingrediente.id_ingrediente = recetas_has_ingrediente.ingrediente","nombreingrediente", ModificarRec.getId());
            comboIng.removeAllItems();

            for (int i = 0; i < aliNom.size(); i++) 
                comboIng.addItem((String) aliNom.get(i));
            
            }
        } else 
            System.out.println("error");
        
    }//GEN-LAST:event_modIngMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked

        Menu men = new Menu();
        this.setVisible(false);
        men.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jlabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlabel1MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel20MouseClicked

    private void LabelCalorias1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelCalorias1MouseClicked
        comActual.setText(ModificarRec.getComentario());

        /**
         * ***
         *
         *
         *
         *
         * ANIMACIONES
         *
         *
         */
    }//GEN-LAST:event_LabelCalorias1MouseClicked

    private void LabelCalorias1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelCalorias1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_LabelCalorias1MouseEntered

    private void LabelCalorias1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelCalorias1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_LabelCalorias1MouseExited

    private void LabelCalorias2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelCalorias2MouseClicked
        descActual.setText(ModificarRec.getDescripcion());

    }//GEN-LAST:event_LabelCalorias2MouseClicked

    private void LabelCalorias2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelCalorias2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_LabelCalorias2MouseEntered

    private void LabelCalorias2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelCalorias2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_LabelCalorias2MouseExited

    private void jLabel24FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel24FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel24FocusGained

    private void modDescMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modDescMouseClicked

        ModificarRec.setNuevaDescripcion(descNueva.getText());

        if (!descNueva.getText().equals("")) {
            if (!descNueva.getText().equals(descActual.getText())) {
                if (sql.updateReceta("UPDATE recetas SET descripcion = ? WHERE id_receta = ?", ModificarRec.getNuevaDescripcion(), ModificarRec.getId())) {
                    System.out.println("success");
                } else {
                    System.out.println("error");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Valor ingresado igual al actual");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Debe ingresar un valor nuevo ");
        }


    }//GEN-LAST:event_modDescMouseClicked

    private void jLabel26FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel26FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel26FocusGained

    private void jLabel28FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel28FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel28FocusGained

    private void modComMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modComMouseClicked

        ModificarRec.setNuevoComentario(comNuevo.getText());
        if (!comNuevo.getText().equals("")) {
            if (!comNuevo.getText().equals(comActual.getText())) {
                if (sql.updateReceta("UPDATE recetas SET comentarioreceta = ? WHERE id_receta = ?", ModificarRec.getNuevoComentario(), ModificarRec.getId())) {
                    System.out.println("success");
                } else {
                    System.out.println("error");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Valor ingresado igual al actual");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Debe ingresar un valor nuevo ");
        }


    }//GEN-LAST:event_modComMouseClicked

    private void jLabel30FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel30FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel30FocusGained

    private void durBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_durBuscarMouseClicked

        ModificarRec.setNuevaDuracion(durNueva.getText());
        if (!durNueva.getText().equals("")) {
            if (!durNueva.getText().equals(durActual.getText())) {
                if (sql.updateReceta("UPDATE recetas SET tiemporeceta = ? WHERE id_receta = ?", ModificarRec.getNuevaDuracion(), ModificarRec.getId())) {
                    System.out.println("success");
                } else {
                    System.out.println("error");
                }

            } else {
                JOptionPane.showMessageDialog(null, "Valor ingresado igual al actual");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Debe ingresar un valor nuevo ");
        }


    }//GEN-LAST:event_durBuscarMouseClicked

    private void actualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actualActionPerformed

    private void comboIngNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboIngNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboIngNuevoActionPerformed

    private void jLabel33FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel33FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel33FocusGained

    private void campoCantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCantActionPerformed

    private void labelCantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelCantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_labelCantActionPerformed

    private void jLabel34FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel34FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel34FocusGained

    private void comboIngItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboIngItemStateChanged
        /*
        //labelCamt
        //labelUni
        int i = comboIng.getSelectedIndex();
        labelCant.setText((String) aliCant.get(i));
        labelUni.setText((String) aliUni.get(i));*/
    }//GEN-LAST:event_comboIngItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BotonModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BotonModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BotonModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BotonModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BotonModificar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BuscarDificultad;
    private javax.swing.JLabel BuscarNombre;
    private javax.swing.JComboBox<String> ComboDificultad;
    private javax.swing.JComboBox<String> ComboTipo;
    private javax.swing.JLabel LabelCalorias1;
    private javax.swing.JLabel LabelCalorias2;
    private javax.swing.JLabel LabelDificultad;
    private javax.swing.JLabel LabelDuracion;
    private javax.swing.JLabel LabelIngrediente;
    private javax.swing.JLabel LabelNombre;
    private javax.swing.JLabel LabelTipo;
    private javax.swing.JPanel PanelBusqueda;
    private javax.swing.JPanel PanelCom;
    private javax.swing.JPanel PanelDesc;
    private javax.swing.JPanel PanelDificultad;
    private javax.swing.JPanel PanelDur;
    private javax.swing.JPanel PanelIngrediente;
    private javax.swing.JPanel PanelNombre;
    private javax.swing.JPanel PanelTipo;
    private javax.swing.JPanel PanelTitulo;
    private javax.swing.JTextField actual;
    private javax.swing.JLabel buscarTipo;
    private javax.swing.JTextField campoCant;
    private javax.swing.JTextArea comActual;
    private javax.swing.JTextArea comNuevo;
    private javax.swing.JComboBox<String> comboIng;
    private javax.swing.JComboBox<String> comboIngNuevo;
    private javax.swing.JComboBox<String> comboUni;
    private javax.swing.JTextArea descActual;
    private javax.swing.JTextArea descNueva;
    private javax.swing.JLabel difActual;
    private javax.swing.JTextField durActual;
    private javax.swing.JLabel durBuscar;
    private javax.swing.JFormattedTextField durNueva;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel jlabel;
    private javax.swing.JLabel jlabel1;
    private javax.swing.JTextField labelCant;
    private javax.swing.JLabel labelPaso;
    private javax.swing.JLabel labelUni;
    private javax.swing.JLabel modCom;
    private javax.swing.JLabel modDesc;
    private javax.swing.JLabel modIng;
    private javax.swing.JTextField nuevo;
    private javax.swing.JLabel tipoActual;
    // End of variables declaration//GEN-END:variables
}
