/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Datos.Buscar;
import Conexion.SQL;
import java.util.ArrayList;
import javax.swing.ImageIcon;

/**
 *
 * @author Rodrigo
 */
public class DetallesBusqueda extends javax.swing.JDialog {

    SQL sql = new SQL();
    
    //declaracion de array's
    ArrayList<String> nombreIngrediente = new ArrayList();
    ArrayList<String> cantidadIngrediente = new ArrayList();
    ArrayList<String> unidadIngrediente = new ArrayList();
    ArrayList<String> pasos = new ArrayList();
    ArrayList caloriasReceta = new ArrayList();
    int index = 1;

    public DetallesBusqueda(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);

        initComponents();
        
        this.setLocationRelativeTo(null);
        try {
            setIconImage(new ImageIcon(getClass().getResource("../Imagenes/icono.png")).getImage());
        } catch (Exception e) {

        }
        areaComentario.setEditable(false);
        areaDescripcion.setEditable(false);
        areaPasos.setEditable(false);
        comboPasos.addItem("Paso 1");

        //igualo array's con metodos
        nombreIngrediente = sql.nombreIngredienteId("SELECT nombreingrediente FROM recetas_has_ingrediente, ingrediente WHERE id_receta = ? and recetas_has_ingrediente.ingrediente = ingrediente.id_ingrediente");
        caloriasReceta = sql.caloriasReceta("SELECT SUM(calorias) FROM ingrediente, recetas_has_ingrediente WHERE id_receta = ? and recetas_has_ingrediente.ingrediente = ingrediente.id_ingrediente");
        cantidadIngrediente = sql.cantidadIngrediente("SELECT cantidad FROM recetas_has_ingrediente, ingrediente WHERE id_receta = ? and recetas_has_ingrediente.ingrediente = ingrediente.id_ingrediente");
        unidadIngrediente = sql.unidadIngrediente("SELECT unidad FROM recetas_has_ingrediente, ingrediente WHERE id_receta = ? and recetas_has_ingrediente.ingrediente = ingrediente.id_ingrediente");
        pasos = sql.traerPasos("SELECT paso FROM pasos, recetas WHERE pasos.id_receta = recetas.id_receta and recetas.id_receta = ?");

        ingrediente.removeAllItems();
        comboPasos.removeAllItems();

        for (int i = 0; i < Buscar.getId().size(); i++) {
            dif.setText(Buscar.getDificultad().get(i));
            usu.setText(Buscar.getUsuario().get(i));
            dur.setText(Buscar.getDuracion().get(i));
            areaComentario.setText(Buscar.getComentario().get(i));
            nom.setText(Buscar.getNombre());
            areaDescripcion.setText(Buscar.getDescripcion().get(i));

        }
        for (int i = 0; i < pasos.size(); i++) {
            comboPasos.addItem("Paso "+index);
            index++;

        }

        for (int j = 0; j < nombreIngrediente.size(); j++) { //agrega el id del ingrediente al combobox
            ingrediente.addItem(nombreIngrediente.get(j) + "   " + cantidadIngrediente.get(j) + " " + unidadIngrediente.get(j));

        }
        for (int i = 0; i < caloriasReceta.size(); i++) {
            cal.setText(String.valueOf(caloriasReceta.get(i)));
        }

        Animacion.Animacion.mover_derecha(-150, 20, 2, 2, jPanel2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        usu = new javax.swing.JLabel();
        dif = new javax.swing.JLabel();
        ingrediente = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dur = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaComentario = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaDescripcion = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cal = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        comboPasos = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        areaPasos = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        nom = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Duración");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 90, 30));

        usu.setText("jLabel1");
        jPanel1.add(usu, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 370, 53, 27));

        dif.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        dif.setForeground(new java.awt.Color(231, 158, 109));
        dif.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dif.setText("Difícil");
        jPanel1.add(dif, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 110, -1));

        ingrediente.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        ingrediente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(ingrediente, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, 170, 39));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-back-24.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Pasos");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, -1, -1));

        dur.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        dur.setForeground(new java.awt.Color(231, 158, 109));
        dur.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dur.setText("12:20");
        jPanel1.add(dur, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 110, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Ingredientes");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, -1, -1));

        areaComentario.setColumns(20);
        areaComentario.setRows(5);
        jScrollPane1.setViewportView(areaComentario);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 240, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Comentarios");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 110, -1));

        areaDescripcion.setColumns(20);
        areaDescripcion.setRows(5);
        jScrollPane2.setViewportView(areaDescripcion);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 180, 100));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Dificultad");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 90, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setText("Calorias");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 80, 30));

        cal.setBackground(new java.awt.Color(0, 0, 0));
        cal.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        cal.setForeground(new java.awt.Color(231, 158, 109));
        cal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cal.setText("120");
        jPanel2.add(cal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 150, 30));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 110, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 150, 130));

        comboPasos.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        comboPasos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboPasos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPasosActionPerformed(evt);
            }
        });
        jPanel1.add(comboPasos, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 150, -1));

        areaPasos.setColumns(20);
        areaPasos.setRows(5);
        jScrollPane3.setViewportView(areaPasos);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, -1, 100));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Descripción");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, -1, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 110, 30));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 110, 30));

        nom.setFont(new java.awt.Font("Montserrat", 0, 36)); // NOI18N
        nom.setForeground(new java.awt.Color(51, 51, 51));
        nom.setText("jLabel10");
        jPanel1.add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 300, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void comboPasosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPasosActionPerformed
       
        int io = 0;
        for (int j = 0; j < comboPasos.getItemCount(); j++) {
            io = comboPasos.getSelectedIndex();
        }
        for (int j = 0; j < pasos.size(); j++) {
            areaPasos.setText(pasos .get(io));
        }
    }//GEN-LAST:event_comboPasosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaComentario;
    private javax.swing.JTextArea areaDescripcion;
    private javax.swing.JTextArea areaPasos;
    private javax.swing.JLabel cal;
    private javax.swing.JComboBox<String> comboPasos;
    private javax.swing.JLabel dif;
    private javax.swing.JLabel dur;
    private javax.swing.JComboBox<String> ingrediente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel nom;
    private javax.swing.JLabel usu;
    // End of variables declaration//GEN-END:variables
}
