/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;
import java.awt.Color;
import Datos.ArrayBusqueda;
import Datos.Buscar;
import Datos.ModificarRec;
import Conexion.SQL;
import Datos.UsuarioTemporal;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Mati
 */
public class ModificarReceta extends javax.swing.JFrame {

    /**
     * Creates new form ModificarReceta
     */    
    ArrayBusqueda busqueda= new ArrayBusqueda();
    Busqueda bus= new Busqueda();
    
    
    SQL sql= new SQL();
    UsuarioTemporal temp = new UsuarioTemporal();
        
    public ModificarReceta() {
        initComponents();
       
        this.setLocationRelativeTo(null);
        try {
            setIconImage(new ImageIcon(getClass().getResource("../Imagenes/icono.png")).getImage());
        } catch (Exception e) {

        }
 
       
        int hola = 0;
        hola = sql.cantidadNombres(temp.getTexto(), "SELECT count(nombre) FROM recetas WHERE nombreusuario = ?");
        System.out.println(busqueda.dificultad2);
        if (hola != 0) {
          
            
            busqueda.dificultad1 = sql.dificultad("SELECT dificultadreceta FROM recetas WHERE nombreusuario = ?", temp.getTexto());
            busqueda.duracion1 = sql.duracionReceta("SELECT tiemporeceta FROM recetas WHERE nombreusuario = ?", temp.getTexto());
            busqueda.id1 = sql.traerId("SELECT id_receta FROM recetas WHERE nombreusuario = ?", temp.getTexto());
            busqueda.usuario1 = sql.usuario("SELECT nombreusuario FROM recetas WHERE nombreusuario = ?", temp.getTexto());
            busqueda.comentario1 = sql.comentarioReceta("SELECT comentarioreceta FROM recetas WHERE nombreusuario = ?", temp.getTexto());
            busqueda.descripcion1 = sql.descripcionReceta("SELECT descripcion FROM recetas WHERE nombreusuario = ?", temp.getTexto());

            busqueda.forPanelesModificar(hola);
            busqueda.cargarPaneles(resultados1);
        } else {
            JOptionPane.showMessageDialog(null, "No hay resultados para su busqueda");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principal = new javax.swing.JPanel();
        displayScroll1 = new javax.swing.JScrollPane();
        resultados1 = new javax.swing.JPanel();
        Titulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BusquedaPor = new javax.swing.JLabel();
        atras = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        displayScroll = new javax.swing.JScrollPane();
        resultados = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        displayScroll1.setBorder(null);

        resultados1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout resultados1Layout = new javax.swing.GroupLayout(resultados1);
        resultados1.setLayout(resultados1Layout);
        resultados1Layout.setHorizontalGroup(
            resultados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        resultados1Layout.setVerticalGroup(
            resultados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        displayScroll1.setViewportView(resultados1);

        principal.add(displayScroll1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 860, 470));

        Titulo.setBackground(new java.awt.Color(255, 102, 102));
        Titulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("RESULTADOS");
        Titulo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, 56));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel2.setText("Búsqueda por: ");
        Titulo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, 81, 31));

        BusquedaPor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BusquedaPor.setText("fdafdsfds");
        Titulo.add(BusquedaPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 70, 102, 31));

        atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-back-50.png"))); // NOI18N
        atras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atrasMouseClicked(evt);
            }
        });
        atras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                atrasKeyPressed(evt);
            }
        });
        Titulo.add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel3.setText("_______________________________________________________________________________________________________________________________________________");
        Titulo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 94, -1, 20));

        principal.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 110));

        getContentPane().add(principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -5, -1, 580));

        resultados.setBackground(new java.awt.Color(255, 255, 255));
        resultados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        displayScroll.setViewportView(resultados);

        getContentPane().add(displayScroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 105, 860, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasMouseClicked
      
    }//GEN-LAST:event_atrasMouseClicked

    private void atrasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_atrasKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_atrasKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BusquedaPor;
    private javax.swing.JPanel Titulo;
    private javax.swing.JLabel atras;
    private javax.swing.JScrollPane displayScroll;
    private javax.swing.JScrollPane displayScroll1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel principal;
    private javax.swing.JPanel resultados;
    private javax.swing.JPanel resultados1;
    // End of variables declaration//GEN-END:variables
}
