/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Datos.Buscar;
import Conexion.SQL;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Rodrigo
 */
public class ResultadosBusqueda extends javax.swing.JPanel {

    ArrayList<String> ali = new ArrayList<String>();
    SQL sql = new SQL();
    DetallesBusqueda b1 = new DetallesBusqueda(new javax.swing.JDialog(), true);
    ArrayList costoReceta = new ArrayList();

    public ResultadosBusqueda() {
        initComponents();

        id.setVisible(false);

        costoReceta = sql.caloriasReceta("SELECT SUM(costo) FROM ingrediente, recetas_has_ingrediente WHERE id_receta = ? and recetas_has_ingrediente.ingrediente = ingrediente.id_ingrediente");
        for (int i = 0; i < Buscar.getId().size(); i++) {
            dif.setText(Buscar.getDificultad().get(i));
            id.setText(Buscar.getId().get(i));
            dur.setText(Buscar.getDuracion().get(i));
            usu.setText(Buscar.getUsuario().get(i));

            if (Buscar.isSeleccionadoNombre() == true) {
                nombre.setText(Buscar.getNombre());
            }
            if (Buscar.isSeleccionadoTipo() == true) {
                nombre.setText(Buscar.getNombrePorTipo().get(i));
            }
            if (Buscar.isSeleccionadoDificultad() == true) {
                nombre.setText(Buscar.getNombrePorDificultad().get(i));
            }
            if (Buscar.isSeleccionadoIngrediente() == true) {
                nombre.setText(Buscar.getNombrePorIngrediente().get(i));
            }
            if (Buscar.isSeleccionadoCalorias() == true) {
                nombre.setText(Buscar.getNombrePorCalorias().get(i));
            }
            if (Buscar.isSeleccionadoCosto() == true) {
                nombre.setText(Buscar.getNombrePorCosto().get(i));
            }
        }
        for (int i = 0; i < costoReceta.size(); i++) {
            dif1.setText(String.valueOf(costoReceta.get(i)));
        }


        /*      
        Buscar b = new Buscar();
        ali = sql.dificultad();
        for (int i = 0; i < ali.size(); i++) {
            //dif.setText(ali.get(1).toString());
           // System.out.println(ali.get(i));
           nombre.setText(ali.get(i));
        }
         */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombre = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dif = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        usu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dur = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dif1 = new javax.swing.JLabel();
        costo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(61, 72, 85));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombre.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        nombre.setForeground(new java.awt.Color(255, 255, 255));
        nombre.setText("Nombre");
        add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 440, 30));

        jLabel2.setText("_______________________________________________________________________________________________________________________________________________");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 139, 860, -1));

        dif.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dif.setForeground(new java.awt.Color(255, 255, 255));
        dif.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dif.setText("dif");
        add(dif, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 90, 20));

        id.setForeground(new java.awt.Color(255, 255, 255));
        id.setText("jLabel3");
        add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        usu.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        usu.setForeground(new java.awt.Color(255, 255, 204));
        usu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usu.setText("jLabel3");
        add(usu, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 150, -1));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Duración");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Creada por");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DETALLES");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 40, -1, -1));

        dur.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dur.setForeground(new java.awt.Color(255, 255, 255));
        dur.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dur.setText("dsadas");
        add(dur, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 100, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botoncitoclaro.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 140, 40));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Dificultad");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, -1, 20));

        dif1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dif1.setForeground(new java.awt.Color(255, 255, 255));
        dif1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dif1.setText("cos");
        add(dif1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 60, 20));

        costo.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        costo.setForeground(new java.awt.Color(255, 255, 255));
        costo.setText("Costo");
        add(costo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 60, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked

        b1.setVisible(true);

    }//GEN-LAST:event_jLabel5MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel costo;
    private javax.swing.JLabel dif;
    private javax.swing.JLabel dif1;
    private javax.swing.JLabel dur;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel usu;
    // End of variables declaration//GEN-END:variables
}
